version: '3'

services:
  node:
    image: quizz-me
    build:
      context: .
      target: dev
    working_dir: /quizzme
    volumes:
      - .:/quizzme
      - /quizzme/node_modules/
    ports:
      - '3000:3000'
    environment: 
      CHOKIDAR_USEPOLLING: "true"
